Add battery icon
bettr-xyz/tracesigma-firmware pull request #68
Opened 2020-06-21 17:13 UTC by fustilio

Made some battery icons to try out placing icon at the top right. Currently overlaps the time and looks a little tall but at least the workflow is roughly laid out.
Using https://github.com/riuson/lcd-image-converter to generate the icon data with the following settings:
    - Preset: Color R5G6B5
    - Block size: 16-bit

TODO: Define when to draw the icons.. but I suppose this will be part of the UI FSM.

Sample images below:
![image](https://user-images.githubusercontent.com/23294131/85230626-07266300-b424-11ea-8347-21100cacbf4f.png)
![image](https://user-images.githubusercontent.com/23294131/85230643-1dccba00-b424-11ea-9e74-e12beade8cbe.png)
![image](https://user-images.githubusercontent.com/23294131/85230816-646ee400-b425-11ea-85d4-0994a4a0a6c7.png)

2020-06-26 18:35 UTC, yongkimleng commented
could we dynamically fill the battery bar based on %?

2020-06-26 18:36 UTC, yongkimleng commented on alpha/icons.h
> +#include <stdint.h>
need the usual #ifndef , #define ... to ensure this only is included once

2020-06-26 18:43 UTC, yongkimleng commented on alpha/icons.h
> +PROGMEM static const uint16_t icon_batt_0[384] = {
we'd have less icons if filling the bar is dynamic

2020-06-26 18:44 UTC, yongkimleng commented on alpha/ui.cpp
> +#define TS_LCD_WIDTH 160
indent

2020-06-26 18:44 UTC, yongkimleng commented on alpha/ui.cpp
> +#define TS_LCD_BORDER 5
Can this be 1 ?

2020-06-26 18:54 UTC, yongkimleng commented on alpha/ui.cpp
> +    uint8_t batt = TS_HAL.power_get_batt_level();
this involves a call to i2c, we should add a local cache that only allows a pull after 10s or so

2020-06-26 18:54 UTC, yongkimleng commented on alpha/ui.cpp
> +    else if (batt >= 65)
why not 60 ?

2020-06-26 18:55 UTC, yongkimleng commented on alpha/ui.cpp
> +    else if (batt >= 65)
maybe 20 50 80

2020-06-26 18:56 UTC, yongkimleng commented on alpha/ui.cpp
> +    uint8_t batt = TS_HAL.power_get_batt_level();
I guess you also need to get charging status and a charging icon

2020-06-26 18:57 UTC, jamesi8086 requested changes
can be improved

2020-07-16 14:32 UTC, fustilio commented
Continued in #83

2020-07-16 14:32 UTC, closed without merging